version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: weather_db
    environment:
      POSTGRES_DB: weather_forecast
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - weather_network

networks:
  weather_network:
    driver: bridge